package com.itech.learnspace.service;

import com.itech.learnspace.dto.UserCreateRequest;
import com.itech.learnspace.entity.SysUser;
import com.itech.learnspace.exception.BusinessException;
import com.itech.learnspace.repository.SysUserRepository;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;

import java.security.SecureRandom;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Service
public class AdminService {

    private static final String PASSWORD_CHARS = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
    private static final SecureRandom RANDOM = new SecureRandom();

    private final SysUserRepository userRepository;
    private final PasswordEncoder passwordEncoder;

    public AdminService(SysUserRepository userRepository, PasswordEncoder passwordEncoder) {
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
    }

    public List<SysUser> listUsers() {
        return userRepository.findAll();
    }

    public Map<String, Object> createUser(UserCreateRequest req) {
        if (userRepository.findByUsername(req.getUsername()).isPresent()) {
            throw new BusinessException("账号已存在");
        }
        boolean autoGenerated = !StringUtils.hasText(req.getPassword());
        String rawPassword = autoGenerated ? generateRandomPassword(6) : req.getPassword();

        SysUser user = new SysUser();
        user.setUsername(req.getUsername());
        user.setPassword(passwordEncoder.encode(rawPassword));
        user.setRealName(req.getRealName());
        user.setRole(req.getRole());
        user.setClassId(req.getClassId());
        user.setStatus(1);
        user = userRepository.save(user);

        Map<String, Object> result = new HashMap<>();
        result.put("user", user);
        if (autoGenerated) {
            result.put("initialPassword", rawPassword);
        }
        return result;
    }

    public SysUser toggleStatus(Long userId) {
        SysUser user = userRepository.findById(userId)
                .orElseThrow(() -> new BusinessException("用户不存在"));
        user.setStatus(user.getStatus() == 1 ? 0 : 1);
        return userRepository.save(user);
    }

    private String generateRandomPassword(int length) {
        StringBuilder sb = new StringBuilder(length);
        for (int i = 0; i < length; i++) {
            sb.append(PASSWORD_CHARS.charAt(RANDOM.nextInt(PASSWORD_CHARS.length())));
        }
        return sb.toString();
    }
}
